### ISSUE TITLE
Thought on having a library?

### ISSUE THREAD

**Issue by lukehinds** [sigstore/sigstore-js#182]
Generally sigstore-xx code repositories are libraries.  What are you thoughts on having a generic library and then a repository for an NPM signing CLI (which consumes from the library)

I ask as I am building something similar in typescript and it would be useful to be able to not have to duplicate a lot of what you have here (get OIDC token, call fulio/rekor, generate keys etc).

I realise you have important fish to fry getting npm on-board and its not likely a good time to refactor, but I figure we can at least kick the tyres over the idea.

**Comment by bdehamer** [comment]
I had always envisioned this package as being the library. There is a bare-bones CLI included here but that's really just for demo/testing purposes. I didn't have plans to build a "real" CLI in JavaScript . . . I figure if someone is looking for a CLI we should point them to `cosign`.

As far as the library-aspect of this is concerned, I'd definitely be interested in any feedback about the public interface which is currently exposed and whether it is meeting the needs of the various consumers.

**Comment by bdehamer** [comment]
I believe this has essentially been completed at this point. The original `sigstore` library has been decomposed into a number of separate packages:

* [`sigstore`](https://github.com/sigstore/sigstore-js/tree/main/packages/client) - Client library implementing Sigstore signing/verification workflows.
* [`@sigstore/bundle`](https://github.com/sigstore/sigstore-js/tree/main/packages/bundle) - TypeScript types and utility functions for working with Sigstore bundles.
* [`@sigstore/cli`](https://github.com/sigstore/sigstore-js/tree/main/packages/cli) - Command line interface for signing/verifying artifacts with Sigstore.
* [`@sigstore/sign`](https://github.com/sigstore/sigstore-js/tree/main/packages/sign) - Library for generating Sigstore signatures.
* [`@sigstore/tuf`](https://github.com/sigstore/sigstore-js/tree/main/packages/tuf) - Library for interacting with the Sigstore TUF repository.

There is also work in-progress to split all of the verification logic into a separate package.
