### ISSUE TITLE
Get TLOG keys from sigstore-js when usedd as a library

### ISSUE THREAD

**Issue by asraa** [sigstore/sigstore-js#215]
https://github.com/sigstore/sigstore-js/blob/825f81ca3d4453cf1252f08d63ee6a164eca9b40/src/tlog/keys.ts#L26

I think that due to this line, when invoking verify outside the CLI with sigstore as a library, this attempts to fetch the rekor.pub from the caller's dir:
`
Error: ENOENT: no such file or directory, open '/home/runner/work/_actions/laurentsimon/slsa-delegator/main/actions/store/rekor.pub'
`

Is there some way to reference the module path? I think I can just get around this by supplying my custom path into my node_modules, but just wanted to flag.

**Comment by laurentsimon** [comment]
using `const pem = fs_1.default.readFileSync(path_1.default.join(__dirname, '../../store/rekor.pub'), 'utf-8');` fixes the path problem if you use `node_modules/` for your dependencies, but fails if using [ncc](https://github.com/vercel/ncc) to compile an application - which is encouraged for GH Actions.

Maybe the rekor.pub should be stored in a variable instead?
