### ISSUE TITLE
json file missing

### ISSUE THREAD

**Issue by laurentsimon** [sigstore/sigstore-js#301]
I get this error when using the library and `ncc` to compile my project: `::error::Cannot find module '../../store/public-good-instance-root.json'`

Problem with tuf-js?

Any pointers? happy to send a PR, but I'm not sure where this file is looked up.

**Comment by asraa** [comment]
This seems like a similar problem to the rekor.pub being distributed - for Ian and Laurent - this file is likely the initial trusted root after which the Rekor/Fulcio key material is fetched from

**Comment by asraa** [comment]
I think this is where it is being read: https://github.com/sigstore/sigstore-js/blob/6ccf8d04a6b8c12e0a2457f217325a022dff7b76/src/tuf/index.ts#L63

There's a small indirection here that probably made codesearch hard. The `public-good-instance-root.json` is fetched from its definition in this `map.json` file that describes the TUF roots: https://github.com/sigstore/sigstore-js/blob/6ccf8d04a6b8c12e0a2457f217325a022dff7b76/store/map.json

**Comment by laurentsimon** [comment]
Thanks Asra, indeed I just did a lazy `grep` which returned nothing :-)

The fix for the rekor.pub was to use `require.resolve` (see https://github.com/sigstore/sigstore-js/pull/216/files) but the code here already uses that.

I wonder whether the indirection makes `ncc` not realize that it needs to copy the file over, or something to this effect. The hard-coded lookup https://github.com/sigstore/sigstore-js/blob/6ccf8d04a6b8c12e0a2457f217325a022dff7b76/src/tuf/index.ts#L46 seems to be working just fine.

**Comment by bdehamer** [comment]
Haven't used `ncc` before, but it does seem that the dynamic nature of the resolution of the `public-good-instance-root.json` makes it so that `ncc` doesn't realize that this file needs to be packed.

After I ran `ncc` on the `sigstore-js` project, I saw that the `require.resolve` for the "map.json" file got re-written to:
```javascript
const mapSrc = __nccwpck_require__.ab + "map.json";
```
while the statement for the "public-good-instance-root.json" was left as:
```javascript
const tufRootSrc = require.resolve(`../../store/${name}-root.json`);
```
Definitely open to suggestions for how to make this more `ncc`-friendly.

**Comment by ianlewis** [comment]
Based on https://github.com/vercel/ncc/issues/74#issuecomment-442836858 we might have better luck with ncc static analysis if the require took the following form. I guess it then could know that anything under `../../store/` should be included?

```javascript
const tufRootFile = `${name}-root.json`
const tufRootSrc = require.resolve(`../../store/' + name);
```

**Comment by bdehamer** [comment]
@ianlewis we haven't yet published the new version (probably next week), but #330 should have resolved this issue.

**Comment by ianlewis** [comment]
> @ianlewis we haven't yet published the new version (probably next week), but #330 should have resolved this issue.

@bdehamer Thanks! I saw your PR. I'll look forward to the new release.

**Comment by bdehamer** [comment]
New version published: https://github.com/sigstore/sigstore-js/releases/tag/v1.1.1
