### ISSUE TITLE
Export sigstore bundle validation

### ISSUE THREAD

**Issue by ianlewis** [sigstore/sigstore-js#380]
I'd like to make use of [sigstore bundle validation](https://github.com/sigstore/sigstore-js/blob/2484d689d9c6f54c0a65c80a9acac771ae5d7ed9/src/types/sigstore/validate.ts#L40) in the npm CLI but it doesn't appear there are any currently exported methods to do that.

I suppose simply calling `verify` would do roughly the same thing but I'd like to be able to validate the format of sigstore bundles without necessarily verifying the signatures, querying Rekor, etc.

**Comment by ianlewis** [comment]
See: https://github.com/npm/cli/pull/6300

**Comment by bdehamer** [comment]
Yeah, seems like a reasonable function to export. Will look at getting a PR together shortly.

**Comment by bdehamer** [comment]
A lot of the bundle-related code was recently extracted into the `@sigstore/bundle` package. This new package exports the [validation function](https://github.com/sigstore/sigstore-js/blob/main/packages/bundle/src/index.ts#L32) used by the `verify` function to check the supplied bundle.
