### ISSUE TITLE
Embed TUF targets to minimize downloads

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/sigstore-js#398]
**Description**

For the Golang library, we embed a copy of the [target files](https://github.com/sigstore/sigstore/tree/main/pkg/tuf/repository/targets), and check if the target file matches the target metadata [here](https://github.com/sigstore/sigstore/blob/main/pkg/tuf/client.go#L522-L527) (a necessary check since the target file may have been updated and would need to be downloaded). Would it be possible to do the same for sigstore-js?

**Comment by bdehamer** [comment]
Yeah, love this idea!
