### ISSUE TITLE
Improving Error Messages, specifically for signing certificate and tlog entry

### ISSUE THREAD

**Issue by enteraga6** [sigstore/sigstore-js#561]
**Describe the issue**
When running a workflow that utilizes sigstore-js to generate a token I received the error messages: "error creating signing certificate" and "error creating tlog entry". Running the workflow again after the first two failures resulted in it generating the token successfully, but I am still confused as to the exact reason why it failed the first two times. To help users identify the source of their problem, I propose improving error messages to provide more detail about the specific issue or failure that occurred. This will give users a better understanding of what went wrong and why, which will make it easier for them to troubleshoot the problem and understand why it occurred.

**Relevant Links**
[Code for "error creating signing certificate"](https://github.com/sigstore/sigstore-js/blob/8db6c5c953478eddb94c40f3df418f46c211f125/packages/client/src/ca/index.ts#L70)
[Code for "error creating tlog entry"](https://github.com/sigstore/sigstore-js/blob/8db6c5c953478eddb94c40f3df418f46c211f125/packages/client/src/tlog/index.ts#L100)

**Context if Needed**
These were my workflow runs:
[Run 1: "error creating tlog entry"
](https://github.com/enteraga6/slsa-lvl3-generic-provenance-with-bazel-example/actions/runs/5272925971/jobs/9535768491)[Run 2: "error creating signing certificate" ](https://github.com/enteraga6/slsa-lvl3-generic-provenance-with-bazel-example/actions/runs/5272937339)

**Comment by bdehamer** [comment]
With the 2.1 release, the specific error text returned by Fulcio/Rekor will now be included in the message of the thrown error.
