### ISSUE TITLE
Sigstore v1.9 not compatible with previous v.1.8 integration

### ISSUE THREAD

**Issue by enteraga6** [sigstore/sigstore-js#833]
**Description**
Hi! In [slsa-github-generator](https://github.com/slsa-framework/slsa-github-generator), we use Sigstore to generate and verify our signing tokens. Our workflows were working with Sigstore `v1.8`, however, when we upgraded to `v1.9`, we experienced issues with the generation and verification of the signing tokens. We were curious if this backwards incompatibility was intentional or not.

The first issue for us lies within the `sign` function. In this [workflow](https://github.com/enteraga6/bazel_docker_test/actions/runs/6631189448/job/18014157037), we see that in v1.9, our [ `sigstore.sign`](https://github.com/slsa-framework/slsa-github-generator/blob/main/actions/delegator/setup-generic/src/main.ts#L136) function fails, not identifying that it is in a GHA workflow.

However, the `attest` function also has the same issue. In this [workflow run](https://github.com/enteraga6/bazel_docker_test/actions/runs/6620691659/job/17983588010), we use v1.8 version of `sign` but use the v1.9 version of [`sigstore.attest`](https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/actions/sign-attestations/src/main.ts#L49), and have the same issue of the not identifying that it is in a GHA workflow on a later job.

Is this functionality the intended behavior? Thank you!

**Version**
Issues with Sigstore v1.9
Expected behavior with Sigstore v1.8

**Comment by bdehamer** [comment]
@enteraga6 there was a little refactoring of the way the identity token is retrieved in v1.9. Looking at your code, I think you just need to remove the `signOptions` altogether:

https://github.com/enteraga6/slsa-github-generator/blob/sigstore-bug/.github/actions/sign-attestations/src/main.ts#L20-L23

Those options were really only intended to be used in scenarios where you want to use the OAuth provider to retrieve an OIDC token.

You can see here that when those options are omitted, it will fallback to using the CI provider (which is the one which knows how to retrieve an OIDC token from GHA:

https://github.com/sigstore/sigstore-js/blob/sigstore%401.9.0/packages/client/src/config.ts#L130-L139

I think the change that may have broken this for you was that it used to always try the CI provider by default as the first strategy for retrieving a token and now it only falls back to that when some other strategy hasn't been configured.
