### ISSUE TITLE
Replace `require.resolve` of `seeds.json` with a `require`

### ISSUE THREAD

**Issue by mmomtchev** [sigstore/sigstore-js#989]
**Description**

`@sigstore/tuf` contains a `require.resolve` for `seeds.json` that can easily be replace with a `require` which can be parsed by bundlers targeting server-less environments.

https://github.com/npm/cli/issues/4291

`@sigstore/tuf` contains one of the blocking `require.resolve` for `@npmcli/arborist` to be bundable.

**Comment by ljharb** [comment]
Why wouldn’t a bundler be able to handle a static require.resolve?

**Comment by mmomtchev** [comment]
That would be a solution, too, yes. But at the moment `ncc` does not do it - as it strives to be a simple solution that just works without any configuration while covering 90% of the use cases.

https://github.com/vercel/ncc/issues/1162

`rollup` could do it if someone was to write a plugin - AFAIK there is no such plugin at the moment.

A generic `rollup` plugin is not that trivial either depending on what it aims to accomplish - for this particular case one could simply copy the file and return a static file name. I wonder if it is possible to inline the file in the bundle and to return some form of encoded URL - but I do not see anything that could work with Node.js.

**Comment by ljharb** [comment]
Seems like ncc fixing this omission would be simpler than attempting to push changes throughout the ecosystem.

**Comment by mmomtchev** [comment]
This up to them of course, but I think that this would be out of their scope - while the change here will be very simple and without consequences.

**Comment by bdehamer** [comment]
Fixed in https://github.com/sigstore/sigstore-js/releases/tag/%40sigstore%2Ftuf%402.3.1

PR to update `pacote`: https://github.com/npm/pacote/pull/345
